spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/somini?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: somini
    password: qwaszx1234!!!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
server:
  port: 8081