spring:
#    datasource:
#      url: jdbc:mysql://127.0.0.1:3306/{testDB}
#      username: 'jieun'
#      password: 'none'
#      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

server:
  port: 8081
