#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/somini?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: somini
#    password: qwaszx1234!!!
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    open-in-view: false
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
##  h2:
#    console:
#      enabled: true
#      path: /console
#  devtools:
#    livereload:
#      enabled: true
#  thymeleaf:
#    cache: false
#server:
#  port: 8083

security:
  jwt:
    token:
      sercret-key: 123@#$
      expire-length: 300000 # 5minutes
#  oauth2:
##    client:
##      client-id: testClientId
##      client-secret: testSecret
##    resource:
##      token-info-uri: http://localhost:8081/oauth/check_token
